name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Ajusting project
      run: rm Makefile
      
    - name: Clone test repo
      run: git clone https://github.com/Talen400/42_gnl_tester.git testers

    - name: Build
      run: | 
          cd tester
          make PROJECT_DIR=../
          
    - name: Run tests
      run: ./test_runner
